- hosts: fortimanagers
  connection: httpapi
  gather_facts: false
  vars:
     ansible_httpapi_use_ssl: True
     ansible_httpapi_validate_certs: False
     ansible_httpapi_port: 443
     adom: root
     obj_policy_name: AWS-HA-Active
  tasks:
    - name: Create new Firewall Address (Dynamic)
      fmgr_firewall_address:
        bypass_validation: true
        adom: "root"
        state: present
        firewall_address:
          name: host_dyn_002
          type: dynamic
          sdn: Test-aws-SDN
          sdn-addr-type: public
          filter: InstanceType=t2.medium
          color: 6
          comment: Created with FortiManager Ansible
          
    - name: ADD VERY BASIC IPV4 POLICY WITH NO NAT (WIDE OPEN)
      fmgr_fwpol_ipv4:
        mode: "set"
        adom: '{{ adom }}'
        package_name: '{{ obj_policy_name }}'
        name: "SDN-Policy"
        comments: "Created by Ansible"
        action: "accept"
        dstaddr: "host_dyn_002"
        srcaddr: "all"
        dstintf: "port1"
        srcintf: "port2"
        logtraffic: "utm"
        service: "ALL"
        schedule: "always"
      ignore_errors: yes
      ignore_unreachable: yes

    - name: Configure external resource.
      fmgr_system_externalresource:
          bypass_validation: False
          adom: '{{ adom }}'
          state: present
          system_externalresource:
            category: 192
            comments:  "Created by Ansible"
            name: threat-feeds-ansible
            refresh-rate: 5
            resource: https://threat-feed-ansible.s3.eu-west-2.amazonaws.com/block.txt
            status: enable
            type: address

    - name: ADD VERY BASIC IPV4 POLICY WITH NO NAT (WIDE OPEN)
      fmgr_fwpol_ipv4:
        mode: "set"
        adom: '{{ adom }}'
        package_name: '{{ obj_policy_name }}'
        name: "threat-feeds-ansible"
        comments: "Created by Ansible"
        action: "accept"
        dstaddr: "threat-feeds-ansible"
        srcaddr: "all"
        dstintf: "port1"
        srcintf: "port2"
        logtraffic: "utm"
        service: "ALL"
        schedule: "always"
      ignore_errors: yes
      ignore_unreachable: yes