- hosts: fortimanagers
  connection: httpapi
  vars:
     ansible_httpapi_use_ssl: True
     ansible_httpapi_validate_certs: False
     ansible_httpapi_port: 443
     adom: root
     obj_policy_name: AWS-HA-Active
  tasks:
  - name: ADD VERY BASIC IPV4 POLICY WITH NO NAT (WIDE OPEN)
    fmgr_fwpol_ipv4:
      mode: "set"
      adom: '{{ adom }}'
      package_name: '{{ obj_policy_name }}'
      name: "Basic_IPv4_Policy"
      comments: "Created by Ansible"
      action: "accept"
      dstaddr: "all"
      srcaddr: "all"
      dstintf: "port1"
      srcintf: "port2"
      logtraffic: "utm"
      service: "ALL"
      schedule: "always"
    ignore_errors: yes
    ignore_unreachable: yes

  - name: create policy in the object
    fmgr_generic:
      method: set
      params:
          - url: "/pm/config/adom/{{ adom }}/pkg/{{ obj_policy_name }}/firewall/policy"
            data:
              name: "policy_one"
              action: "accept"
              srcintf: 'port1'
              dstintf: 'port2'
              srcaddr: "all"
              dstaddr: "all"
              service: "ALL"
              schedule: "always"
    register: policyinfo
    failed_when: policyinfo.rc != 0 and policyinfo.rc != -9998

  # - name: create an address object
  #   fmgr_generic:
  #     method: set
  #     params:
  #         - url: "/pm/config/adom/{{ adom }}/obj/firewall/address"
  #           data:
  #             - name: "IPMask"
  #               comment: "address object created via generic ansible module"
  #               type: "ipmask"
  #               visibility: "enable"
  #               subnet: "22.33.44.55/32"  